# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :vsrx1 do |vsrx1|
    vsrx1.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
    vsrx1.vm.network "private_network", ip: "10.0.1.1", netmask: "255.255.255.0", virtualbox__intnet: "private1"
  end

  config.vm.define :iosxrv1 do |iosxrv1|
    iosxrv1.vm.box = "IOS-XRv"
    iosxrv1.vm.network "private_network", ip: "10.0.1.2", netmask: "255.255.255.0", virtualbox__intnet: "private1"
  end

end
