- hosts: vsrx1
  connection: local
  gather_facts: no
  tasks:
    - name: Load and commit vsrx1
      junos_config:
        src: sample_config_junos.txt
        comment: update config
        provider: "{{ netconf }}"